version: '2.2'

services:

  p3dx:
    image: lucyannofrota/p3dx-noetic-foxy:latest
    container_name: p3dx
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
    command: >
      bash -c "  
        (. noetic/devel/setup.bash && roscore) &
        (sleep 15 && . noetic/devel/setup.bash && rosparam load noetic/config/ros1_bridge.yaml && roslaunch p3dx_bringup p3dx_bringup.launch) & 
        (sleep 25 && . foxy/install/setup.bash && ros2 run ros1_bridge parameter_bridge) & 
        (sleep 30 && . foxy/install/setup.bash && python3 /workspace/foxy/src/e_stop/gpio_node.py)
      "

  p3dx-navigation:
    network_mode: "host"
    image: lucyannofrota/p3dx-navigation:latest
    container_name: p3dx-navigation
    privileged: true
    depends_on:
      - p3dx
    environment:
      - "ROS_DOMAIN_ID=5"
    restart: unless-stopped
    command: >
      bash -c "
        sleep 40 && . install/setup.bash && ros2 launch p3dx_bringup bringup_slam_launch.py
      "

  smap-sampler:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-sampler-zed
    container_name: smap-sampler-zed
    privileged: true
    depends_on:
      - p3dx-navigation
    environment:
      - "ROS_DOMAIN_ID=5"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        sleep 40 && . install/setup.bash && 
        (
          (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0]) & configs:
          (ros2 launch smap_sampler sampler_launch.py)
        )
      "

  smap-deploy:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-deploy-latest
    container_name: smap-core
    privileged: true
    depends_on:
      - p3dx
      - p3dx-navigation
      - smap-sampler
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_node smap_launch.py
      "

  smap-env:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-deploy-latest
    container_name: smap-env
    privileged: true
    depends_on:
      - p3dx
      - p3dx-navigation
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
      - ./results/timers/object_estimator:/workspace/src/smap/smap_core/timers/object_estimator
      - ./results/timers/topo_map:/workspace/src/smap/smap_core/timers/topo_map
      - ./results/vals/object_estimator:/workspace/src/smap/smap_core/vals/object_estimator
      - ./results/maps:/workspace/src/smap/smap_core/maps
      - ./results/maps/g_maps:/workspace/src/smap/smap_core/maps/g_maps
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        tail -f /dev/null
      "

  smap-yolov5:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./results/timers/yolo_v5:/workspace/timers/yolo_v5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_launch.py
      "
    
  smap-yolov5-even:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5-even
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./results/timers/yolo_v5_even:/workspace/timers/yolo_v5_even
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_even_launch.py
      "

  smap-yolov5-odd:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5-odd
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./results/timers/yolo_v5_odd:/workspace/timers/yolo_v5_odd
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_odd_launch.py
      "
